---
applications:
  dsm_filling.create_dtm: # the first application uses bulldozer, creating a DTM
    method: bulldozer
    classification:
    - "6"
  dsm_filling.use_dtm: # the second application uses the DTM created earlier
    method: border_interpolation
    classification:
    - "10"
