---
applications:
  dsm_filling.1:
    method: exogenous_filling
    classification:
    - "8"
    fill_with_geoid:
    - "8"
    save_intermediate_data: true
  dsm_filling.2:
    method: bulldozer
    classification:
    - "6"
    save_intermediate_data: true
  dsm_filling.3:
    method: border_interpolation
    classification:
    - "7"
    save_intermediate_data: true
